00:21:26 Traceback (most recent call last):
  File "/home/bhavik/frappe-bench/env/lib/python3.10/site-packages/rq/worker.py", line 1061, in perform_job
    rv = job.perform()
  File "/home/bhavik/frappe-bench/env/lib/python3.10/site-packages/rq/job.py", line 821, in perform
    self._result = self._execute()
  File "/home/bhavik/frappe-bench/env/lib/python3.10/site-packages/rq/job.py", line 844, in _execute
    result = self.func(*self.args, **self.kwargs)
  File "/home/bhavik/frappe-bench/apps/frappe/frappe/utils/background_jobs.py", line 160, in execute_job
    method(**kwargs)
  File "/home/bhavik/frappe-bench/apps/frappe/frappe/core/doctype/user/user.py", line 1109, in create_contact
    contact.insert(
  File "/home/bhavik/frappe-bench/apps/frappe/frappe/model/document.py", line 249, in insert
    self._validate_links()
  File "/home/bhavik/frappe-bench/apps/frappe/frappe/model/document.py", line 898, in _validate_links
    frappe.throw(_("Could not find {0}").format(msg), frappe.LinkValidationError)
  File "/home/bhavik/frappe-bench/apps/frappe/frappe/__init__.py", line 522, in throw
    msgprint(
  File "/home/bhavik/frappe-bench/apps/frappe/frappe/__init__.py", line 490, in msgprint
    _raise_exception()
  File "/home/bhavik/frappe-bench/apps/frappe/frappe/__init__.py", line 442, in _raise_exception
    raise raise_exception(msg)
frappe.exceptions.LinkValidationError: Could not find User Id: bhavik@navkar.biz
Traceback (most recent call last):
  File "/home/bhavik/frappe-bench/env/lib/python3.10/site-packages/rq/worker.py", line 1061, in perform_job
    rv = job.perform()
  File "/home/bhavik/frappe-bench/env/lib/python3.10/site-packages/rq/job.py", line 821, in perform
    self._result = self._execute()
  File "/home/bhavik/frappe-bench/env/lib/python3.10/site-packages/rq/job.py", line 844, in _execute
    result = self.func(*self.args, **self.kwargs)
  File "/home/bhavik/frappe-bench/apps/frappe/frappe/utils/background_jobs.py", line 160, in execute_job
    method(**kwargs)
  File "/home/bhavik/frappe-bench/apps/frappe/frappe/core/doctype/user/user.py", line 1109, in create_contact
    contact.insert(
  File "/home/bhavik/frappe-bench/apps/frappe/frappe/model/document.py", line 249, in insert
    self._validate_links()
  File "/home/bhavik/frappe-bench/apps/frappe/frappe/model/document.py", line 898, in _validate_links
    frappe.throw(_("Could not find {0}").format(msg), frappe.LinkValidationError)
  File "/home/bhavik/frappe-bench/apps/frappe/frappe/__init__.py", line 522, in throw
    msgprint(
  File "/home/bhavik/frappe-bench/apps/frappe/frappe/__init__.py", line 490, in msgprint
    _raise_exception()
  File "/home/bhavik/frappe-bench/apps/frappe/frappe/__init__.py", line 442, in _raise_exception
    raise raise_exception(msg)
frappe.exceptions.LinkValidationError: Could not find User Id: bhavik@navkar.biz
00:21:27 Traceback (most recent call last):
  File "/home/bhavik/frappe-bench/env/lib/python3.10/site-packages/rq/worker.py", line 1061, in perform_job
    rv = job.perform()
  File "/home/bhavik/frappe-bench/env/lib/python3.10/site-packages/rq/job.py", line 821, in perform
    self._result = self._execute()
  File "/home/bhavik/frappe-bench/env/lib/python3.10/site-packages/rq/job.py", line 844, in _execute
    result = self.func(*self.args, **self.kwargs)
  File "/home/bhavik/frappe-bench/apps/frappe/frappe/utils/background_jobs.py", line 160, in execute_job
    method(**kwargs)
  File "/home/bhavik/frappe-bench/apps/frappe/frappe/core/doctype/user/user.py", line 1109, in create_contact
    contact.insert(
  File "/home/bhavik/frappe-bench/apps/frappe/frappe/model/document.py", line 249, in insert
    self._validate_links()
  File "/home/bhavik/frappe-bench/apps/frappe/frappe/model/document.py", line 898, in _validate_links
    frappe.throw(_("Could not find {0}").format(msg), frappe.LinkValidationError)
  File "/home/bhavik/frappe-bench/apps/frappe/frappe/__init__.py", line 522, in throw
    msgprint(
  File "/home/bhavik/frappe-bench/apps/frappe/frappe/__init__.py", line 490, in msgprint
    _raise_exception()
  File "/home/bhavik/frappe-bench/apps/frappe/frappe/__init__.py", line 442, in _raise_exception
    raise raise_exception(msg)
frappe.exceptions.LinkValidationError: Could not find User Id: bhavik@navkar.biz
Traceback (most recent call last):
  File "/home/bhavik/frappe-bench/env/lib/python3.10/site-packages/rq/worker.py", line 1061, in perform_job
    rv = job.perform()
  File "/home/bhavik/frappe-bench/env/lib/python3.10/site-packages/rq/job.py", line 821, in perform
    self._result = self._execute()
  File "/home/bhavik/frappe-bench/env/lib/python3.10/site-packages/rq/job.py", line 844, in _execute
    result = self.func(*self.args, **self.kwargs)
  File "/home/bhavik/frappe-bench/apps/frappe/frappe/utils/background_jobs.py", line 160, in execute_job
    method(**kwargs)
  File "/home/bhavik/frappe-bench/apps/frappe/frappe/core/doctype/user/user.py", line 1109, in create_contact
    contact.insert(
  File "/home/bhavik/frappe-bench/apps/frappe/frappe/model/document.py", line 249, in insert
    self._validate_links()
  File "/home/bhavik/frappe-bench/apps/frappe/frappe/model/document.py", line 898, in _validate_links
    frappe.throw(_("Could not find {0}").format(msg), frappe.LinkValidationError)
  File "/home/bhavik/frappe-bench/apps/frappe/frappe/__init__.py", line 522, in throw
    msgprint(
  File "/home/bhavik/frappe-bench/apps/frappe/frappe/__init__.py", line 490, in msgprint
    _raise_exception()
  File "/home/bhavik/frappe-bench/apps/frappe/frappe/__init__.py", line 442, in _raise_exception
    raise raise_exception(msg)
frappe.exceptions.LinkValidationError: Could not find User Id: bhavik@navkar.biz
12:03:13 Traceback (most recent call last):
  File "/home/bhavik/frappe-bench/apps/frappe/frappe/utils/caching.py", line 55, in wrapper
    return frappe.local.request_cache[func][args_key]
KeyError: 7326490903468949957

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/bhavik/frappe-bench/apps/frappe/frappe/__init__.py", line 1445, in _load_app_hooks
    app_hooks = get_module(f"{app}.hooks")
  File "/home/bhavik/frappe-bench/apps/frappe/frappe/__init__.py", line 1323, in get_module
    return importlib.import_module(modulename)
  File "/usr/lib/python3.10/importlib/__init__.py", line 126, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 1050, in _gcd_import
  File "<frozen importlib._bootstrap>", line 1027, in _find_and_load
  File "<frozen importlib._bootstrap>", line 1006, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 688, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 883, in exec_module
  File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
  File "/home/bhavik/frappe-bench/apps/employeewise_payroll/employeewise_payroll/hooks.py", line 3, in <module>
    PayrollEntry = get_controller("Payroll Entry")
  File "/home/bhavik/frappe-bench/apps/frappe/frappe/model/base_document.py", line 81, in get_controller
    site_controllers[doctype] = _get_controller()
  File "/home/bhavik/frappe-bench/apps/frappe/frappe/model/base_document.py", line 59, in _get_controller
    module = frappe.get_module(module_path)
  File "/home/bhavik/frappe-bench/apps/frappe/frappe/__init__.py", line 1323, in get_module
    return importlib.import_module(modulename)
  File "/usr/lib/python3.10/importlib/__init__.py", line 126, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 1050, in _gcd_import
  File "<frozen importlib._bootstrap>", line 1027, in _find_and_load
  File "<frozen importlib._bootstrap>", line 1006, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 688, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 883, in exec_module
  File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
  File "/home/bhavik/frappe-bench/apps/employeewise_payroll/employeewise_payroll/employeewise_payroll/payroll_entry/__init__.py", line 1, in <module>
    from .payroll_entry import CustomPayrollEntry, cash_payment, payroll_payment_entry_exists
  File "/home/bhavik/frappe-bench/apps/employeewise_payroll/employeewise_payroll/employeewise_payroll/payroll_entry/payroll_entry.py", line 3, in <module>
    from employeewise_payroll.hooks import PayrollEntry
ImportError: cannot import name 'PayrollEntry' from partially initialized module 'employeewise_payroll.hooks' (most likely due to a circular import) (/home/bhavik/frappe-bench/apps/employeewise_payroll/employeewise_payroll/hooks.py)

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/bhavik/frappe-bench/env/lib/python3.10/site-packages/rq/worker.py", line 1061, in perform_job
    rv = job.perform()
  File "/home/bhavik/frappe-bench/env/lib/python3.10/site-packages/rq/job.py", line 821, in perform
    self._result = self._execute()
  File "/home/bhavik/frappe-bench/env/lib/python3.10/site-packages/rq/job.py", line 844, in _execute
    result = self.func(*self.args, **self.kwargs)
  File "/home/bhavik/frappe-bench/apps/frappe/frappe/utils/background_jobs.py", line 160, in execute_job
    method(**kwargs)
  File "/home/bhavik/frappe-bench/apps/frappe/frappe/core/doctype/scheduled_job_type/scheduled_job_type.py", line 136, in run_scheduled_job
    frappe.get_doc("Scheduled Job Type", dict(method=job_type)).execute()
  File "/home/bhavik/frappe-bench/apps/frappe/frappe/core/doctype/scheduled_job_type/scheduled_job_type.py", line 88, in execute
    frappe.get_attr(self.method)()
  File "/home/bhavik/frappe-bench/apps/frappe/frappe/utils/change_log.py", line 169, in check_for_update
    apps = get_versions()
  File "/home/bhavik/frappe-bench/apps/frappe/frappe/utils/change_log.py", line 112, in get_versions
    app_hooks = frappe.get_hooks(app_name=app)
  File "/home/bhavik/frappe-bench/apps/frappe/frappe/__init__.py", line 1471, in get_hooks
    hooks = _dict(_load_app_hooks(app_name))
  File "/home/bhavik/frappe-bench/apps/frappe/frappe/utils/caching.py", line 57, in wrapper
    return_val = func(*args, **kwargs)
  File "/home/bhavik/frappe-bench/apps/frappe/frappe/__init__.py", line 1453, in _load_app_hooks
    raise SystemExit
SystemExit
Traceback (most recent call last):
  File "/home/bhavik/frappe-bench/apps/frappe/frappe/utils/caching.py", line 55, in wrapper
    return frappe.local.request_cache[func][args_key]
KeyError: 7326490903468949957

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/bhavik/frappe-bench/apps/frappe/frappe/__init__.py", line 1445, in _load_app_hooks
    app_hooks = get_module(f"{app}.hooks")
  File "/home/bhavik/frappe-bench/apps/frappe/frappe/__init__.py", line 1323, in get_module
    return importlib.import_module(modulename)
  File "/usr/lib/python3.10/importlib/__init__.py", line 126, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 1050, in _gcd_import
  File "<frozen importlib._bootstrap>", line 1027, in _find_and_load
  File "<frozen importlib._bootstrap>", line 1006, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 688, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 883, in exec_module
  File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
  File "/home/bhavik/frappe-bench/apps/employeewise_payroll/employeewise_payroll/hooks.py", line 3, in <module>
    PayrollEntry = get_controller("Payroll Entry")
  File "/home/bhavik/frappe-bench/apps/frappe/frappe/model/base_document.py", line 81, in get_controller
    site_controllers[doctype] = _get_controller()
  File "/home/bhavik/frappe-bench/apps/frappe/frappe/model/base_document.py", line 59, in _get_controller
    module = frappe.get_module(module_path)
  File "/home/bhavik/frappe-bench/apps/frappe/frappe/__init__.py", line 1323, in get_module
    return importlib.import_module(modulename)
  File "/usr/lib/python3.10/importlib/__init__.py", line 126, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 1050, in _gcd_import
  File "<frozen importlib._bootstrap>", line 1027, in _find_and_load
  File "<frozen importlib._bootstrap>", line 1006, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 688, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 883, in exec_module
  File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
  File "/home/bhavik/frappe-bench/apps/employeewise_payroll/employeewise_payroll/employeewise_payroll/payroll_entry/__init__.py", line 1, in <module>
    from .payroll_entry import CustomPayrollEntry, cash_payment, payroll_payment_entry_exists
  File "/home/bhavik/frappe-bench/apps/employeewise_payroll/employeewise_payroll/employeewise_payroll/payroll_entry/payroll_entry.py", line 3, in <module>
    from employeewise_payroll.hooks import PayrollEntry
ImportError: cannot import name 'PayrollEntry' from partially initialized module 'employeewise_payroll.hooks' (most likely due to a circular import) (/home/bhavik/frappe-bench/apps/employeewise_payroll/employeewise_payroll/hooks.py)

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/bhavik/frappe-bench/env/lib/python3.10/site-packages/rq/worker.py", line 1061, in perform_job
    rv = job.perform()
  File "/home/bhavik/frappe-bench/env/lib/python3.10/site-packages/rq/job.py", line 821, in perform
    self._result = self._execute()
  File "/home/bhavik/frappe-bench/env/lib/python3.10/site-packages/rq/job.py", line 844, in _execute
    result = self.func(*self.args, **self.kwargs)
  File "/home/bhavik/frappe-bench/apps/frappe/frappe/utils/background_jobs.py", line 160, in execute_job
    method(**kwargs)
  File "/home/bhavik/frappe-bench/apps/frappe/frappe/core/doctype/scheduled_job_type/scheduled_job_type.py", line 136, in run_scheduled_job
    frappe.get_doc("Scheduled Job Type", dict(method=job_type)).execute()
  File "/home/bhavik/frappe-bench/apps/frappe/frappe/core/doctype/scheduled_job_type/scheduled_job_type.py", line 88, in execute
    frappe.get_attr(self.method)()
  File "/home/bhavik/frappe-bench/apps/frappe/frappe/utils/change_log.py", line 169, in check_for_update
    apps = get_versions()
  File "/home/bhavik/frappe-bench/apps/frappe/frappe/utils/change_log.py", line 112, in get_versions
    app_hooks = frappe.get_hooks(app_name=app)
  File "/home/bhavik/frappe-bench/apps/frappe/frappe/__init__.py", line 1471, in get_hooks
    hooks = _dict(_load_app_hooks(app_name))
  File "/home/bhavik/frappe-bench/apps/frappe/frappe/utils/caching.py", line 57, in wrapper
    return_val = func(*args, **kwargs)
  File "/home/bhavik/frappe-bench/apps/frappe/frappe/__init__.py", line 1453, in _load_app_hooks
    raise SystemExit
SystemExit
12:20:01 Traceback (most recent call last):
  File "/home/bhavik/frappe-bench/env/lib/python3.10/site-packages/rq/worker.py", line 1061, in perform_job
    rv = job.perform()
  File "/home/bhavik/frappe-bench/env/lib/python3.10/site-packages/rq/job.py", line 821, in perform
    self._result = self._execute()
  File "/home/bhavik/frappe-bench/env/lib/python3.10/site-packages/rq/job.py", line 844, in _execute
    result = self.func(*self.args, **self.kwargs)
  File "/home/bhavik/frappe-bench/apps/frappe/frappe/utils/background_jobs.py", line 160, in execute_job
    method(**kwargs)
  File "/home/bhavik/frappe-bench/apps/frappe/frappe/core/doctype/user/user.py", line 1109, in create_contact
    contact.insert(
  File "/home/bhavik/frappe-bench/apps/frappe/frappe/model/document.py", line 249, in insert
    self._validate_links()
  File "/home/bhavik/frappe-bench/apps/frappe/frappe/model/document.py", line 898, in _validate_links
    frappe.throw(_("Could not find {0}").format(msg), frappe.LinkValidationError)
  File "/home/bhavik/frappe-bench/apps/frappe/frappe/__init__.py", line 522, in throw
    msgprint(
  File "/home/bhavik/frappe-bench/apps/frappe/frappe/__init__.py", line 490, in msgprint
    _raise_exception()
  File "/home/bhavik/frappe-bench/apps/frappe/frappe/__init__.py", line 442, in _raise_exception
    raise raise_exception(msg)
frappe.exceptions.LinkValidationError: Could not find User Id: bhavik@navkar.biz
Traceback (most recent call last):
  File "/home/bhavik/frappe-bench/env/lib/python3.10/site-packages/rq/worker.py", line 1061, in perform_job
    rv = job.perform()
  File "/home/bhavik/frappe-bench/env/lib/python3.10/site-packages/rq/job.py", line 821, in perform
    self._result = self._execute()
  File "/home/bhavik/frappe-bench/env/lib/python3.10/site-packages/rq/job.py", line 844, in _execute
    result = self.func(*self.args, **self.kwargs)
  File "/home/bhavik/frappe-bench/apps/frappe/frappe/utils/background_jobs.py", line 160, in execute_job
    method(**kwargs)
  File "/home/bhavik/frappe-bench/apps/frappe/frappe/core/doctype/user/user.py", line 1109, in create_contact
    contact.insert(
  File "/home/bhavik/frappe-bench/apps/frappe/frappe/model/document.py", line 249, in insert
    self._validate_links()
  File "/home/bhavik/frappe-bench/apps/frappe/frappe/model/document.py", line 898, in _validate_links
    frappe.throw(_("Could not find {0}").format(msg), frappe.LinkValidationError)
  File "/home/bhavik/frappe-bench/apps/frappe/frappe/__init__.py", line 522, in throw
    msgprint(
  File "/home/bhavik/frappe-bench/apps/frappe/frappe/__init__.py", line 490, in msgprint
    _raise_exception()
  File "/home/bhavik/frappe-bench/apps/frappe/frappe/__init__.py", line 442, in _raise_exception
    raise raise_exception(msg)
frappe.exceptions.LinkValidationError: Could not find User Id: bhavik@navkar.biz
12:20:01 Traceback (most recent call last):
  File "/home/bhavik/frappe-bench/env/lib/python3.10/site-packages/rq/worker.py", line 1061, in perform_job
    rv = job.perform()
  File "/home/bhavik/frappe-bench/env/lib/python3.10/site-packages/rq/job.py", line 821, in perform
    self._result = self._execute()
  File "/home/bhavik/frappe-bench/env/lib/python3.10/site-packages/rq/job.py", line 844, in _execute
    result = self.func(*self.args, **self.kwargs)
  File "/home/bhavik/frappe-bench/apps/frappe/frappe/utils/background_jobs.py", line 160, in execute_job
    method(**kwargs)
  File "/home/bhavik/frappe-bench/apps/frappe/frappe/core/doctype/user/user.py", line 1109, in create_contact
    contact.insert(
  File "/home/bhavik/frappe-bench/apps/frappe/frappe/model/document.py", line 249, in insert
    self._validate_links()
  File "/home/bhavik/frappe-bench/apps/frappe/frappe/model/document.py", line 898, in _validate_links
    frappe.throw(_("Could not find {0}").format(msg), frappe.LinkValidationError)
  File "/home/bhavik/frappe-bench/apps/frappe/frappe/__init__.py", line 522, in throw
    msgprint(
  File "/home/bhavik/frappe-bench/apps/frappe/frappe/__init__.py", line 490, in msgprint
    _raise_exception()
  File "/home/bhavik/frappe-bench/apps/frappe/frappe/__init__.py", line 442, in _raise_exception
    raise raise_exception(msg)
frappe.exceptions.LinkValidationError: Could not find User Id: bhavik@navkar.biz
Traceback (most recent call last):
  File "/home/bhavik/frappe-bench/env/lib/python3.10/site-packages/rq/worker.py", line 1061, in perform_job
    rv = job.perform()
  File "/home/bhavik/frappe-bench/env/lib/python3.10/site-packages/rq/job.py", line 821, in perform
    self._result = self._execute()
  File "/home/bhavik/frappe-bench/env/lib/python3.10/site-packages/rq/job.py", line 844, in _execute
    result = self.func(*self.args, **self.kwargs)
  File "/home/bhavik/frappe-bench/apps/frappe/frappe/utils/background_jobs.py", line 160, in execute_job
    method(**kwargs)
  File "/home/bhavik/frappe-bench/apps/frappe/frappe/core/doctype/user/user.py", line 1109, in create_contact
    contact.insert(
  File "/home/bhavik/frappe-bench/apps/frappe/frappe/model/document.py", line 249, in insert
    self._validate_links()
  File "/home/bhavik/frappe-bench/apps/frappe/frappe/model/document.py", line 898, in _validate_links
    frappe.throw(_("Could not find {0}").format(msg), frappe.LinkValidationError)
  File "/home/bhavik/frappe-bench/apps/frappe/frappe/__init__.py", line 522, in throw
    msgprint(
  File "/home/bhavik/frappe-bench/apps/frappe/frappe/__init__.py", line 490, in msgprint
    _raise_exception()
  File "/home/bhavik/frappe-bench/apps/frappe/frappe/__init__.py", line 442, in _raise_exception
    raise raise_exception(msg)
frappe.exceptions.LinkValidationError: Could not find User Id: bhavik@navkar.biz
